version: "3.8"
services:
    mysql:
        image: mysql:5.7
        working_dir: /application
        volumes:
            - ../:/application
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
            - MYSQL_DATABASE=test_task
        ports:
            - "3306:3306"

    nginx:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ../:/application
            - "./nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ../var/log/nginx:/var/log/nginx
        ports:
            - "80:80"

    php:
        build: php-fpm
        working_dir: /application
        volumes:
            - ../:/application
